# Generated by Django 5.0.1 on 2025-11-05 00:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mrn', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='MRN must be exactly 6 digits', regex='^\\d{6}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'patients',
                'indexes': [models.Index(fields=['mrn'], name='patients_mrn_5d1fc1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('npi', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='NPI must be exactly 10 digits', regex='^\\d{10}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'providers',
                'indexes': [models.Index(fields=['npi'], name='providers_npi_df1406_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_diagnosis', models.CharField(max_length=20)),
                ('additional_diagnoses', models.JSONField(blank=True, default=list)),
                ('medication_name', models.CharField(max_length=200)),
                ('medication_history', models.JSONField(blank=True, default=list)),
                ('patient_records', models.TextField()),
                ('care_plan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.provider')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
