# Generated by Django 5.0.1 on 2025-11-05 00:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='npi',
            field=models.CharField(help_text='National Provider Identifier - unique 10-digit number (one per provider)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='NPI must be exactly 10 digits', regex='^\\d{10}$')]),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(fields=('npi',), name='unique_provider_npi'),
        ),
    ]
