# Generated by Django 5.0.1 on 2025-11-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_provider_npi_provider_unique_provider_npi'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='care_plan_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
